version: '3'

networks: 
    wow:

volumes: 
    data:
        driver: local

services:
    webserver:
        image: nginx:stable
        container_name: webserver
        restart: unless-stopped
        tty: true
        volumes: 
            - ./src:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - "80:80"
            - "443:443"
        depends_on: 
            - app
        networks: 
            - wow
    
    mysql:
        image: mariadb
        container_name: wow-db
        tty: true
        ports: 
            - 3306:3306
        volumes: 
            - data:/var/lib/mysql
            - ./dump:/dump
        environment: 
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: wow
            SERVICE_NAME: mysql
            SERVICE_TAGS: dev
        networks: 
            - wow
    
    app:
        image: mauro/laravel:php74
        container_name: wow-combat
        tty: true
        ports: 
            - 8000:8000
        volumes: 
            - ./src:/var/www
        working_dir: /var/www
        depends_on: 
            - mysql
        networks: 
            - wow